import Head from "next/head";
import AboutAcademy from "../components/AboutAcademy";
import Academy from "../components/Academy";
import Navbar from "../components/Navbar";
import Regestry from "../components/Regestry";

const academy = () => {
  return (
    <div>
      <Head>
        <title>DJKINGHER || Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.png" />
      </Head>
      <main>
        <Navbar />
        <AboutAcademy />
        <Regestry />
      </main>
    </div>
  );
};

export default academy;
